"""
Arnaud et al. (2010) universal GNFW pressure profile, parameterised by M_200m.

The A10 profile is natively defined on M_500c, so an NFW-based mass conversion
is performed internally (concentration from Duffy et al. 2008, 200-mean fit,
or user-supplied).

Dependencies: numpy, matplotlib.  Root-finding is a local bisection.

** Generated by Claude Code and not manually verified **
"""

import numpy as np
import matplotlib.pyplot as plt

# ----------------------------------------------------------------- constants
RHO_C0 = 2.77536627e11          # h^2 Msun / Mpc^3
KEVCM3_TO_ERGCM3 = 1.602176634e-9
N_GAS_OVER_N_E = 1.83           # A10 convention: P_thermal = 1.83 n_e k T

# A10 best-fit GNFW shape parameters (their Eq. 12 / Appendix B), h70 units
A10 = dict(P0=8.403, c500=1.177, gamma=0.3081, alpha=1.0510, beta=5.4905)
ALPHA_P = 0.12                  # mass-dependence break from self-similarity

# A10 calibration range in r/r_500c (X-ray data; beyond ~1 it is a
# simulation-informed extrapolation, valid to ~3 r_500c)
A10_XRAY_RANGE = (0.03, 1.0)


# ----------------------------------------------------------------- cosmology
class Cosmology:
    def __init__(self, h=0.674, Om=0.315):
        self.h, self.Om, self.Ol = h, Om, 1.0 - Om

    def E(self, z):
        return np.sqrt(self.Om * (1.0 + z) ** 3 + self.Ol)

    def rho_c(self, z):
        """Critical density [Msun / Mpc^3]."""
        return RHO_C0 * self.h ** 2 * self.E(z) ** 2

    def rho_m(self, z):
        """Mean matter density [Msun / Mpc^3]."""
        return RHO_C0 * self.h ** 2 * self.Om * (1.0 + z) ** 3


# ------------------------------------------------------------- mass converter
def _nfw_mu(y):
    return np.log1p(y) - y / (1.0 + y)


def duffy_c200m(M200m, z, cosmo):
    """Duffy et al. (2008) full-sample c(M) for Delta = 200 rho_mean."""
    Mpivot = 2e12 / cosmo.h                      # Msun
    return 10.14 * (M200m / Mpivot) ** -0.081 * (1.0 + z) ** -1.01


def _bisect(f, lo, hi, tol=1e-10, itmax=200):
    flo = f(lo)
    for _ in range(itmax):
        mid = 0.5 * (lo + hi)
        fmid = f(mid)
        if fmid == 0.0 or (hi - lo) < tol * mid:
            return mid
        if np.sign(fmid) == np.sign(flo):
            lo, flo = mid, fmid
        else:
            hi = mid
    return 0.5 * (lo + hi)


def convert_200m_to_500c(M200m, z, cosmo, c200m=None):
    """
    Convert M_200m -> M_500c assuming an NFW profile.

    Returns (M500c [Msun], R500c [Mpc], R200m [Mpc], c200m).
    """
    if c200m is None:
        c200m = duffy_c200m(M200m, z, cosmo)

    R200m = (3.0 * M200m / (4.0 * np.pi * 200.0 * cosmo.rho_m(z))) ** (1.0 / 3.0)
    rs = R200m / c200m
    norm = M200m / _nfw_mu(c200m)                # = 4 pi rho_s rs^3

    def f(R):
        return norm * _nfw_mu(R / rs) - (4.0 / 3.0) * np.pi * R ** 3 * 500.0 * cosmo.rho_c(z)

    R500c = _bisect(f, 1e-4 * R200m, R200m)
    M500c = (4.0 / 3.0) * np.pi * R500c ** 3 * 500.0 * cosmo.rho_c(z)
    return M500c, R500c, R200m, c200m


# ------------------------------------------------------------ A10 profile
def _gnfw(x, h70):
    c = A10["c500"] * x
    P0 = A10["P0"] * h70 ** -1.5
    return P0 / (c ** A10["gamma"] *
                 (1.0 + c ** A10["alpha"]) ** ((A10["beta"] - A10["gamma"]) / A10["alpha"]))


def arnaud_pressure(r, M200m, z=0.0, cosmo=None, c200m=None,
                    component="total", radial_alpha_p=True, units="erg"):
    """
    Thermal pressure of the A10 universal profile.

    Parameters
    ----------
    r        : radius/radii [Mpc] (physical, not comoving)
    M200m    : halo mass [Msun]
    component: 'total' (n_gas k T, the A10 definition) or 'electron' (n_e k T)
    radial_alpha_p : include the radially-varying alpha_p'(x) correction
    units    : 'erg' -> erg/cm^3, 'keV' -> keV/cm^3

    Returns
    -------
    P, info   where info is a dict of derived halo quantities.
    """
    cosmo = cosmo or Cosmology()
    h70 = cosmo.h / 0.7
    M500c, R500c, R200m, c200m = convert_200m_to_500c(M200m, z, cosmo, c200m)

    x = np.atleast_1d(np.asarray(r, dtype=float)) / R500c
    Mratio = M500c / (3e14 / h70)                # A10 pivot, h70^-1 Msun

    P500 = 1.65e-3 * cosmo.E(z) ** (8.0 / 3.0) * Mratio ** (2.0 / 3.0) * h70 ** 2

    expo = ALPHA_P
    if radial_alpha_p:
        expo = expo + 0.10 - (ALPHA_P + 0.10) * (x / 0.5) ** 3 / (1.0 + (x / 0.5) ** 3)

    P = P500 * _gnfw(x, h70) * Mratio ** expo    # keV / cm^3

    if component == "electron":
        P = P / N_GAS_OVER_N_E
    elif component != "total":
        raise ValueError("component must be 'total' or 'electron'")

    if units == "erg":
        P = P * KEVCM3_TO_ERGCM3
    elif units != "keV":
        raise ValueError("units must be 'erg' or 'keV'")

    info = dict(M500c=M500c, R500c=R500c, R200m=R200m, c200m=c200m,
                P500_keVcm3=P500, x=x)
    return (P[0] if np.isscalar(r) else P), info


# ------------------------------------------------------------------ plotting
def plot_arnaud_profile(M200m, z=0.0, cosmo=None, xaxis="r200m",
                        component="total", units="erg", xlim=(0.02, 2.0),
                        n=400, ax=None, label=None, **kwargs):
    """
    Plot P(r) for a halo of mass M200m.

    xaxis : 'r200m' -> abscissa is r/R_200m
            'Mpc'   -> abscissa is physical r in Mpc
    xlim  : range in units of R_200m (always), converted internally.
    """
    cosmo = cosmo or Cosmology()
    _, _, R200m, _ = convert_200m_to_500c(M200m, z, cosmo)

    frac = np.logspace(np.log10(xlim[0]), np.log10(xlim[1]), n)
    r = frac * R200m
    P, info = arnaud_pressure(r, M200m, z, cosmo, component=component, units=units)

    xdata = frac if xaxis == "r200m" else r
    if xaxis not in ("r200m", "Mpc"):
        raise ValueError("xaxis must be 'r200m' or 'Mpc'")

    if ax is None:
        ax = p.gca()

    if label is None:
        label = rf"$M_{{200m}}={M200m:.1e}\,M_\odot$, $z={z:g}$"

    # split calibrated vs extrapolated (in r/r_500c)
    calib = info["x"] <= A10_XRAY_RANGE[1]
    line, = ax.loglog(xdata[calib], P[calib], label=label, **kwargs)
    #ax.loglog(xdata[~calib], P[~calib], alpha=0.2, color=line.get_color(), **kwargs)

    #for R, name in ((info["R500c"], r"$r_{500c}$"), (R200m, r"$r_{200m}$")):
    #    xv = R / R200m if xaxis == "r200m" else R
    #    ax.axvline(xv, color="0.7", lw=0.8, zorder=0)
    #    ax.annotate(name, (xv, 0.97), xycoords=("data", "axes fraction"),
    #                ha="right", va="top", fontsize=8, color="0.4", rotation=90)

    ax.set_xlabel(r"$r / r_{200m}$" if xaxis == "r200m" else r"$r\ \mathrm{[Mpc]}$")
    plab = "P_\\mathrm{e}" if component == "electron" else "P_\\mathrm{th}"
    ulab = r"\mathrm{erg\,cm^{-3}}" if units == "erg" else r"\mathrm{keV\,cm^{-3}}"
    ax.set_ylabel(rf"${plab}\ [{ulab}]$")
    #ax.legend(frameon=False, fontsize=9)
    #ax.grid(alpha=0.25, which="both", lw=0.4)
    return ax, r, P, info


if __name__ == "__main__":
    cos = Cosmology()
    fig, axes = plt.subplots(1, 2, figsize=(11, 4.4))
    for M in (1e14, 5e14, 2e15):
        plot_arnaud_profile(M, z=0.0, cosmo=cos, xaxis="r200m", ax=axes[0])
        plot_arnaud_profile(M, z=0.0, cosmo=cos, xaxis="Mpc", ax=axes[1])
    fig.tight_layout()
    fig.savefig("arnaud_profile.png", dpi=140)

    for M in (1e14, 5e14, 2e15):
        P, info = arnaud_pressure(0.5, M, 0.0, cos)
        print(f"M200m={M:.1e}  M500c={info['M500c']:.3e}  R500c={info['R500c']:.3f} Mpc  "
              f"R200m={info['R200m']:.3f} Mpc  c200m={info['c200m']:.2f}  "
              f"P(0.5Mpc)={P:.3e} erg/cm^3")