"""Stacked FLAMINGO halo profiles for the tSZ thermostat paper (Peiris et al.).

This module produces the simulation measurements contributed to the tSZ thermostat
paper. It is the production version of the ad-hoc notebook cells that produced the
first delivery, ``flamingo_pressure_profiles.csv``; that table is reproduced here
bit-for-bit as deliverable ``pressure_z0.4`` (see "Verification" below), so the new
outputs and the one already in use are generated by the same code path.

The stacking itself is done by :mod:`flamingo_analysis` against a tangos database of
FLAMINGO halo profiles. What this module adds is the set of choices that define the
deliverable -- box, redshift, mass binning, units, and the halo statistics needed to
interpret each stack -- together with a self-describing JSON serialisation.


What is being measured
----------------------

For each halo, the simulation database stores a radial profile of a gas property,
computed in 50 logarithmically spaced radial shells and volume-weighted within each
shell. A *stack* is the unweighted mean of those profiles over all haloes in a mass
bin: a mean of profiles, not a profile of the mean halo. Each stack is reported on two
radial binnings, distinguished by the ``panel`` field:

``relative``
    Shells spaced logarithmically over 0.05 to 5.0 r200m, so each halo is stacked in
    units of its own r200m. This is the binning to use for anything scale-free.

``absolute``
    Shells spaced logarithmically over 0.05 to 5.0 Mpc (50 to 5000 kpc), physical, the
    same shells for every halo. Haloes of different size therefore contribute
    different parts of their structure to a given shell.

The reported ``x`` values are shell centres in log space, i.e. the geometric centre of
each shell, not the shell edges.

Empty shells are excluded from the mean rather than counted as zero. For pressure,
temperature and entropy this is the physically meaningful choice, since an empty shell
has no defined pressure; it does mean that in the sparsely populated outskirts a stack
is a mean over a shrinking subset of haloes. About 3% of shells are empty overall.
Density is the exception and is handled differently -- see "Density" below.

No selection beyond the mass cut is applied: all haloes in the bin enter the stack,
centrals and satellites alike, with no relaxedness or substructure cut.

A mass bin containing no haloes produces no stack rather than an empty one, so a mass
ladder is not guaranteed to be complete at every redshift. The only case here is the
>10^14 Msol bin at z = 2, where the box contains no such halo.


Mass binning
------------

Haloes are binned by M200m -- the mass within the radius enclosing 200 times the *mean*
matter density -- computed live from the halo catalogue. This is not the mass
definition used for pressure-profile fitting in the literature (usually M500c), and the
two are not interchangeable; any comparison must convert explicitly, using a
concentration relation consistent with the rest of the calculation.

The top bin of a mass ladder is open-ended. In JSON, its upper edge is serialised as
``null`` rather than infinity, which strict JSON cannot represent.

Because the mass bins are wide and the halo mass function is steep, a stack is not
representative of the mass at the centre of its bin: it is dominated by haloes near the
bin's lower edge. Each stack therefore carries ``n_halos`` and the mean and median
log10 M200m of its members, so the stack-effective mass can be used rather than
inferred. This matters most for the open top bin.


Units and cosmology
-------------------

Pressure is thermal pressure in erg cm^-3; the conversion from the database's internal
units is computed from pynbody rather than hardcoded. Density is gas mass density in
Msol kpc^-3. Radii are r/r200m (dimensionless) or physical Mpc. Masses are Msol.

All boxes here run the FLAMINGO fiducial D3A (DES-Y3) cosmology of Schaye et al. 2023
(arXiv:2306.04024), Tables 3-4, recorded in ``COSMOLOGY`` below. Note that this is not
the Planck cosmology used for work facing Efstathiou & McCarthy (2025); only ratios
transfer across that boundary.


Resolution and box size
-----------------------

Two resolutions appear here, and they must not be mixed in an absolute comparison:

``m8``  ``L0200N0720`` -- 200 Mpc box, 720^3 particles.
``m9``  ``L0200N0360`` -- 200 Mpc box, 360^3 particles.

The mean interparticle spacing sets the particle mass, so ``L0200N0720`` has the same
particle mass as the production m8 box ``L1000N3600``, and ``L0200N0360`` the same as
the production m9 box ``L1000N1800``. They are *not* those boxes: at 200 Mpc on a side
these have 1/125 of the production volume. The consequence is that there are no rich
clusters. The most massive halo at z = 0.4 is 10^14.65 Msol, and only 75 haloes exceed
10^14 Msol. Statements about clusters rest on tens of objects, not thousands.

The AGN variants exist only at m9. Comparing a variant to the m8 fiducial therefore
confounds feedback with resolution, so the variant deliverable also includes the m9
fiducial as a matched-resolution control: take variant-to-control ratios at fixed
resolution rather than differencing against the m8 stacks.


Density
-------

The database holds two distinct gas density profiles, and only one of them is suitable
for a hydrostatic test:

``gas_density``
    Shell mass divided by shell volume. Consistent with ``gas_mass_enclosed``, and zero
    (not undefined) in an empty shell, so empty shells enter the stack as zeros and the
    mean remains an unbiased mass estimator. **This is what we output.**

``gas_rho``
    The volume-weighted mean of the SPH density field over the particles in the shell.
    Undefined in an empty shell, and not constrained to integrate to the enclosed mass.
    Not used here.


The deliverables
----------------

``pressure_z0.4``
    The original delivery, reproduced. Pressure, m8 fiducial, z = 0.4, four mass bins.

``pressure_redshifts`` (task 1)
    Pressure, m8 fiducial, the same mass bins, at all nine available redshifts
    (z = 0 to 2). The request was for one additional redshift; the full series costs
    the same and lets the evolution be fitted rather than differenced. Note that the
    cluster stack thins out quickly with redshift -- 75 haloes above 10^14 Msol at
    z = 0.4, 35 at z = 0.75, 13 at z = 1.0 -- so ``n_halos`` should be consulted before
    using the top bin at high redshift. z = 0.75 is the last redshift with a usable
    cluster stack.

``pressure_massive_split`` (task 2)
    Pressure, m8 fiducial, z = 0.4, with the open >10^14 bin split. The split is at
    10^14.25, not the 10^14.5 originally suggested: the box's most massive halo is
    10^14.65, so a cut at 10^14.5 leaves 9 haloes above it, whereas 10^14.25 divides
    the 75 haloes into 44 and 31.

``pressure_fine_bins`` (task 3)
    Pressure, m8 fiducial, z = 0.4, with 0.25 dex bins spanning 10^13.5 to 10^14, which
    brackets the critical mass 10^13.76. The neighbouring bins are kept unchanged for
    context.

``density_z0.4`` (task 4)
    Gas density, m8 fiducial, z = 0.4, the original mass bins and radial range.

``pressure_variants`` (task 5)
    Pressure, z = 0.4, original mass bins, for the fgas-8sigma (``STRONGEST_AGN``) and
    Jet-4sigma (``JETS_STRONGER_AGN``) feedback variants, plus the m9 fiducial as a
    matched-resolution control. All m9 -- see "Resolution and box size".


JSON schema
-----------

Each deliverable is one JSON object::

    {
      "description":  what this file contains, in prose,
      "task":         which request it answers,
      "purpose":      why it was asked for,
      "generated_by": the command that produced it,
      "generated_on": UTC date,
      "quantity":     "pressure" or "density",
      "value_column": name of the per-stack value field, e.g. "pressure_erg_cm3",
      "units":        {...},
      "cosmology":    {...},
      "conventions":  {...},
      "caveats":      [ ... ],
      "stacks":       [ ... ]
    }

and each entry of ``stacks`` is::

    {
      "simulation", "variant", "resolution",     which box
      "redshift", "snapshot",                    which snapshot
      "mass_definition": "M200m",
      "M_min_log10Msol", "M_max_log10Msol",      bin edges; upper is null if open
      "mass_bin":                                human-readable label
      "n_halos",                                 haloes entering the stack
      "mean_log10_M200m", "median_log10_M200m",  stack-effective mass
      "mean_r200m_kpc",                          mean r200m of the members, physical
      "panel": "relative" | "absolute",
      "x_units": "r/r200m" | "Mpc",
      "x":            [50 shell centres],
      <value_column>: [50 stacked values]
    }


Verification
------------

``--verify`` regenerates the ``pressure_z0.4`` deliverable and compares it against the
CSV already delivered to the collaboration. Agreement is at the level of floating-point
round-off (~3e-16 fractional), confirming that this module and the original notebook
cells are the same measurement.

The comparison checks that the two tables describe the same rows in the same order
before comparing values, so a change to the mass or radial binning is reported as a
structural mismatch rather than showing up as large residuals.


Usage
-----

::

    python sz_paper_profile_extraction.py --list
    python sz_paper_profile_extraction.py --verify
    python sz_paper_profile_extraction.py --all --outdir sz_paper_profiles
    python sz_paper_profile_extraction.py --deliverable pressure_redshifts
"""

import argparse
import datetime
import json
import os

import numpy as np
import pandas as pd
import pynbody
import tangos as db

import flamingo_analysis as fa

# ---------------------------------------------------------------------------
# Simulations
# ---------------------------------------------------------------------------

DEFAULT_DB = 'data.db'

#: box -> (variant label, resolution). See "Resolution and box size" in the docstring.
SIMULATIONS = {
    "L0200N0720_HYDRO_FIDUCIAL": ("fiducial", "m8"),
    "L0200N0360_HYDRO_FIDUCIAL": ("fiducial", "m9"),
    "L0200N0360_HYDRO_STRONGEST_AGN": ("fgas-8sigma", "m9"),
    "L0200N0360_HYDRO_JETS_STRONGER_AGN": ("Jet-4sigma", "m9"),
}

M8_FIDUCIAL = "L0200N0720_HYDRO_FIDUCIAL"

#: Snapshot number for each redshift. Identical across all boxes here.
TSNUM_BY_REDSHIFT = {2.0: 0, 1.0: 1, 0.75: 2, 0.5: 3, 0.4: 4,
                     0.3: 5, 0.2: 6, 0.1: 7, 0.0: 8}

#: The redshift of the first delivery, and of everything except the redshift series.
DEFAULT_REDSHIFT = 0.4

#: FLAMINGO fiducial D3A (DES-Y3) cosmology, Schaye et al. 2023 Tables 3-4.
COSMOLOGY = {
    "name": "FLAMINGO fiducial D3A (DES-Y3)",
    "reference": "Schaye et al. 2023 (arXiv:2306.04024), Tables 3-4",
    "h": 0.681, "Omega_m": 0.306, "Omega_Lambda": 0.694, "Omega_b": 0.0486,
    "sum_m_nu_eV": 0.06, "A_s": 2.099e-9, "n_s": 0.967, "sigma_8": 0.807,
}

# ---------------------------------------------------------------------------
# Binning
# ---------------------------------------------------------------------------

#: Mass bins of the original delivery, in log10(M200m/Msol), descending.
MASS_BINS = [(12.5, 13.0), (13.0, 13.5), (13.5, 14.0), (14.0, np.inf)][::-1]

#: Top bin split at 10^14.25 rather than 10^14.5 -- see the docstring, task 2.
MASS_BINS_SPLIT_TOP = [(12.5, 13.0), (13.0, 13.5), (13.5, 14.0),
                       (14.0, 14.25), (14.25, np.inf)][::-1]

#: 0.25 dex bins bracketing the critical mass, 10^13.76.
MASS_BINS_FINE = [(12.5, 13.0), (13.0, 13.5), (13.5, 13.75), (13.75, 14.0),
                  (14.0, np.inf)][::-1]

MASS_NAME = "M200m()"
MASS_DEFINITION = "M200m"

#: Critical mass of the thermostat at z = 0.4, for orientation only.
LOG10_M_CRIT = 13.76

#: Radial binning, fixed by the property classes in flamingo_tangos.
RADIAL_BINNING = {
    "n_bins": 50,
    "spacing": "logarithmic, values reported at shell centres in log space",
    "relative": {"min": 0.05, "max": 5.0, "units": "r/r200m"},
    "absolute": {"min": 0.05, "max": 5.0, "units": "Mpc"},
}

# ---------------------------------------------------------------------------
# Quantities
# ---------------------------------------------------------------------------

#: Thermal pressure, internal units (Msol km^2 s^-2 kpc^-3) -> erg cm^-3.
PRESSURE_TO_ERG_CM3 = pynbody.units.Unit('Msol km^2 s^-2 kpc^-3').in_units('erg cm^-3')

QUANTITIES = {
    'pressure': dict(
        property='p', particle='gas', rescale=PRESSURE_TO_ERG_CM3,
        column='pressure_erg_cm3', unit='erg cm^-3',
        description="Thermal gas pressure, volume-weighted within each radial shell.",
    ),
    'density': dict(
        property='density', particle='gas', rescale=1.0,
        column='density_Msol_kpc3', unit='Msol kpc^-3',
        description="Gas mass density: shell mass divided by shell volume, "
                    "consistent with the enclosed-mass profile.",
    ),
}

# ---------------------------------------------------------------------------
# Deliverables
# ---------------------------------------------------------------------------

DELIVERABLES = {
    'pressure_z0.4': dict(
        task="Original delivery, reproduced",
        purpose="The stacks already in use, regenerated by this script so that "
                "everything is produced by one code path.",
        quantity='pressure', boxes=[M8_FIDUCIAL], redshifts=[0.4], mass_bins=MASS_BINS,
    ),
    'pressure_redshifts': dict(
        task="1. Second redshift",
        purpose="Measure the evolution of the atmospheres above the critical mass, "
                "which the prediction currently assumes self-similar.",
        quantity='pressure', boxes=[M8_FIDUCIAL],
        redshifts=sorted(TSNUM_BY_REDSHIFT), mass_bins=MASS_BINS,
    ),
    'pressure_massive_split': dict(
        task="2. Split of the top mass bin",
        purpose="Separate 'clusters are ~15% dimmer than the Arnaud profile at their "
                "true mass' from brightness introduced by the mass-definition "
                "conversion.",
        quantity='pressure', boxes=[M8_FIDUCIAL], redshifts=[DEFAULT_REDSHIFT],
        mass_bins=MASS_BINS_SPLIT_TOP,
    ),
    'pressure_fine_bins': dict(
        task="3. Finer bins across the critical mass",
        purpose="Test whether the smooth recovery of the gas fraction hides a "
                f"transition at M_crit = 10^{LOG10_M_CRIT} Msol.",
        quantity='pressure', boxes=[M8_FIDUCIAL], redshifts=[DEFAULT_REDSHIFT],
        mass_bins=MASS_BINS_FINE,
    ),
    'density_z0.4': dict(
        task="4. Density-profile stacks",
        purpose="Test the hydrostatic assumption directly, and localise the 7-12% "
                "brightness bias just below the critical mass.",
        quantity='density', boxes=[M8_FIDUCIAL], redshifts=[DEFAULT_REDSHIFT],
        mass_bins=MASS_BINS,
    ),
    'pressure_variants': dict(
        task="5. Variant pressure stacks",
        purpose="Validate the variant predictions against measured stacks instead of "
                "by reconstruction alone.",
        quantity='pressure',
        boxes=["L0200N0360_HYDRO_STRONGEST_AGN", "L0200N0360_HYDRO_JETS_STRONGER_AGN",
               "L0200N0360_HYDRO_FIDUCIAL"],
        redshifts=[DEFAULT_REDSHIFT], mass_bins=MASS_BINS,
    ),
}

#: Caveats attached to every file, plus those triggered by a deliverable's content.
GENERAL_CAVEATS = [
    "M200m is not interchangeable with M500c; convert explicitly, using a "
    "concentration relation consistent with the rest of the calculation.",
    "Mass bins are wide and the mass function is steep, so each stack is dominated by "
    "haloes near its lower edge. Use mean_log10_M200m, not the bin centre.",
    "The box is 200 Mpc on a side, so there are no rich clusters: the most massive "
    "halo at z = 0.4 is 10^14.65 Msol.",
    "No relaxedness or substructure cut is applied; centrals and satellites both enter.",
    "A mass bin containing no haloes is omitted rather than emitted empty, so check "
    "that the ladder you expect is present before differencing across redshift.",
]

EMPTY_SHELL_CAVEAT = (
    "Empty shells are excluded from the mean rather than counted as zero, so in the "
    "outskirts a stack is a mean over a shrinking subset of haloes (~3% of shells "
    "overall are empty)."
)

MIXED_RESOLUTION_CAVEAT = (
    "These are m9 boxes, whereas the delivered fiducial stacks are m8. Compare "
    "variants to the m9 fiducial control included here, as ratios; do not difference "
    "them against the m8 stacks, which would confound feedback with resolution."
)

OPEN_TOP_BIN_CAVEAT = (
    "The upper edge of the open top bin is serialised as null."
)


# ---------------------------------------------------------------------------
# Stacking
# ---------------------------------------------------------------------------

def _timestep_name(box, redshift):
    try:
        tsnum = TSNUM_BY_REDSHIFT[redshift]
    except KeyError:
        raise ValueError(f"No snapshot at z={redshift}; "
                         f"available: {sorted(TSNUM_BY_REDSHIFT)}") from None
    return f"{box}/%{tsnum}.hdf5", tsnum


def _profile_property_name(quantity, panel):
    """The tangos property name that flamingo_analysis will stack for this panel."""
    spec = QUANTITIES[quantity]
    name = spec['property'] + ('_r200m_relative' if panel == 'relative' else '')
    return f"{spec['particle']}_{name}"


def _halo_statistics(timestep_name, prop_name, mass_bins, _cache={}):
    """Number and mass of the haloes entering each stack.

    The halo set is defined by a joint query for the profile property alongside M200m,
    so it is exactly the set flamingo_analysis stacks, and the mass cut repeats the one
    applied there.
    """
    key = (timestep_name, prop_name)
    if key not in _cache:
        ts = db.get_timestep(timestep_name)
        _, M200m, r200m = ts.calculate_all(prop_name, MASS_NAME, 'r200m')
        _cache[key] = (M200m, r200m)
    M200m, r200m = _cache[key]

    statistics = []
    for M_min, M_max in mass_bins:
        mask = (M200m > 10 ** M_min) * (M200m < 10 ** M_max)
        n = int(mask.sum())
        statistics.append({
            'n_halos': n,
            'mean_log10_M200m': float(np.log10(M200m[mask]).mean()) if n else None,
            'median_log10_M200m': float(np.median(np.log10(M200m[mask]))) if n else None,
            'mean_r200m_kpc': float(r200m[mask].mean()) if n else None,
        })
    return statistics


def stack(quantity='pressure', box=M8_FIDUCIAL, redshift=DEFAULT_REDSHIFT,
          mass_bins=None):
    """Stack one quantity in one snapshot, and return a list of stack records.

    One record per (panel, mass bin). See the module docstring for the schema.
    """
    if mass_bins is None:
        mass_bins = MASS_BINS
    spec = QUANTITIES[quantity]
    variant, resolution = SIMULATIONS[box]
    timestep_name, tsnum = _timestep_name(box, redshift)

    # flamingo_analysis takes the log of each profile to form an error estimate, which
    # we discard; for density that means log(0) in empty shells. The mean profile we do
    # keep is unaffected, so silence the warning rather than let it reach the user.
    with np.errstate(divide='ignore', invalid='ignore'):
        table = fa.tabulate_profile_plot_data(
            spec['property'], tsnum=tsnum, box=box, particle=spec['particle'],
            rescale=spec['rescale'], ranges_override=list(mass_bins),
            mass_name=MASS_NAME,
            # The bootstrap only sets the error range, which we do not tabulate.
            # Skipping it leaves the mean profiles bit-for-bit identical, and is
            # much faster.
            get_stack_kwargs={'bootstrap': False},
        )
    table = table.rename(columns={spec['property']: spec['column']})

    records = []
    for panel in ('relative', 'absolute'):
        statistics = _halo_statistics(timestep_name,
                                      _profile_property_name(quantity, panel), mass_bins)
        for (M_min, M_max), stats in zip(mass_bins, statistics):
            rows = table[(table['panel'] == panel)
                         & (table['M_min_log10Msol'] == M_min)
                         & (table['M_max_log10Msol'] == M_max)]
            if len(rows) == 0:
                continue
            records.append({
                'simulation': box, 'variant': variant, 'resolution': resolution,
                'redshift': redshift, 'snapshot': tsnum,
                'mass_definition': MASS_DEFINITION,
                'M_min_log10Msol': float(M_min),
                'M_max_log10Msol': None if np.isinf(M_max) else float(M_max),
                'mass_bin': rows['mass_bin'].iloc[0],
                **stats,
                'panel': panel,
                'x_units': rows['x_units'].iloc[0],
                'x': rows['x'].tolist(),
                spec['column']: rows[spec['column']].tolist(),
            })
    return records


def build(name, command=None):
    """Assemble one named deliverable as a JSON-serialisable dict."""
    if name not in DELIVERABLES:
        raise ValueError(f"Unknown deliverable {name!r}; "
                         f"available: {sorted(DELIVERABLES)}")
    definition = DELIVERABLES[name]
    spec = QUANTITIES[definition['quantity']]

    stacks = []
    for box in definition['boxes']:
        for redshift in definition['redshifts']:
            stacks += stack(quantity=definition['quantity'], box=box,
                            redshift=redshift, mass_bins=definition['mass_bins'])

    caveats = list(GENERAL_CAVEATS)
    if definition['quantity'] != 'density':
        caveats.append(EMPTY_SHELL_CAVEAT)
    if len({SIMULATIONS[b][1] for b in definition['boxes']}) > 1 or \
            any(SIMULATIONS[b][1] == 'm9' for b in definition['boxes']):
        caveats.append(MIXED_RESOLUTION_CAVEAT)
    if any(np.isinf(M_max) for _, M_max in definition['mass_bins']):
        caveats.append(OPEN_TOP_BIN_CAVEAT)

    return {
        'description': _describe(name, definition),
        'task': definition['task'],
        'purpose': definition['purpose'],
        'generated_by': command or f"sz_paper_profile_extraction.py --deliverable {name}",
        'generated_on': datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%d'),
        'source': "FLAMINGO halo profiles, stacked with flamingo_analysis.py "
                  "(the machinery of Pontzen et al. 2026, arXiv:2605.16483)",
        'quantity': definition['quantity'],
        'value_column': spec['column'],
        'value_description': spec['description'],
        'units': {
            'value': spec['unit'],
            'x_relative': 'r/r200m (dimensionless)',
            'x_absolute': 'Mpc (physical)',
            'mass': 'Msol', 'radius': 'kpc (physical)',
        },
        'radial_binning': RADIAL_BINNING,
        'cosmology': COSMOLOGY,
        'conventions': {
            'stack': "unweighted mean over haloes of the individual halo profiles, "
                     "each volume-weighted within its radial shells",
            'mass_definition': "M200m, the mass within the radius enclosing 200 times "
                               "the mean matter density",
            'log10_M_crit_z0.4': LOG10_M_CRIT,
        },
        'caveats': caveats,
        'n_stacks': len(stacks),
        'stacks': stacks,
    }


def _describe(name, definition):
    quantity = QUANTITIES[definition['quantity']]['description'].rstrip('.')
    boxes = ", ".join(f"{b} ({SIMULATIONS[b][0]}, {SIMULATIONS[b][1]})"
                      for b in definition['boxes'])
    redshifts = definition['redshifts']
    z = (f"z = {redshifts[0]}" if len(redshifts) == 1
         else f"z = {min(redshifts)} to {max(redshifts)} ({len(redshifts)} snapshots)")
    edges = sorted({e for bin in definition['mass_bins'] for e in bin
                    if not np.isinf(e)})
    return (f"{quantity}, stacked in bins of M200m. Simulations: {boxes}. {z}. "
            f"Mass bin edges (log10 M200m/Msol): "
            f"{', '.join(f'{e:g}' for e in edges)}, and above.")


# ---------------------------------------------------------------------------
# Verification against the first delivery
# ---------------------------------------------------------------------------

REFERENCE_CSV = 'flamingo-tsz-thermostat/data/flamingo_pressure_profiles.csv'


def verify(reference_path=REFERENCE_CSV, rtol=1e-10):
    """Check that the pressure_z0.4 deliverable reproduces the delivered CSV.

    Returns (agrees, message).
    """
    document = build('pressure_z0.4')
    value_column = document['value_column']

    rows = []
    for s in document['stacks']:
        for x, value in zip(s['x'], s[value_column]):
            rows.append({'panel': s['panel'], 'mass_bin': s['mass_bin'],
                         'M_min_log10Msol': s['M_min_log10Msol'],
                         'M_max_log10Msol': np.inf if s['M_max_log10Msol'] is None
                                            else s['M_max_log10Msol'],
                         'x_units': s['x_units'], 'x': x, value_column: value})
    table = pd.DataFrame(rows)
    reference = pd.read_csv(reference_path).rename(
        columns={'pressure_erg_cm3': value_column})

    if len(reference) != len(table):
        return False, f"row count mismatch: reference {len(reference)}, new {len(table)}"
    for column in ['panel', 'mass_bin', 'M_min_log10Msol', 'M_max_log10Msol', 'x_units']:
        if not (reference[column].astype(str).values
                == table[column].astype(str).values).all():
            return False, f"rows do not line up: '{column}' differs"

    lines, agrees = [], True
    for column in ['x', value_column]:
        old, new = reference[column].values, table[column].values
        with np.errstate(divide='ignore', invalid='ignore'):
            worst = np.nanmax(np.abs(new - old) / np.abs(old))
        lines.append(f"  {column:>18s}: max |delta|/|ref| = {worst:.3e}")
        agrees &= bool(worst <= rtol)
    return agrees, "\n".join(lines)


# ---------------------------------------------------------------------------
# Command line
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Produce the stacked FLAMINGO profiles contributed to the tSZ "
                    "thermostat paper. See the module docstring for what is in them.")
    parser.add_argument('--deliverable', action='append', metavar='NAME',
                        choices=sorted(DELIVERABLES),
                        help="produce this deliverable (repeatable)")
    parser.add_argument('--all', action='store_true', help="produce every deliverable")
    parser.add_argument('--list', action='store_true',
                        help="list the deliverables and exit")
    parser.add_argument('--outdir', default='sz_paper_profiles',
                        help="directory for the JSON files (default: sz_paper_profiles)")
    parser.add_argument('--db', default=DEFAULT_DB,
                        help=f"tangos database (default: {DEFAULT_DB})")
    parser.add_argument('--verify', action='store_true',
                        help="check that pressure_z0.4 reproduces the delivered CSV")
    parser.add_argument('--reference', default=REFERENCE_CSV,
                        help="the delivered CSV that --verify compares against")
    args = parser.parse_args()

    if args.list:
        for name, definition in DELIVERABLES.items():
            print(f"{name}\n    {definition['task']}\n    {definition['purpose']}\n")
        return 0

    db.init_db(args.db)

    if args.verify:
        agrees, message = verify(args.reference)
        print(f"pressure_z0.4 against {args.reference}:")
        print(message)
        print("AGREES" if agrees else "DOES NOT AGREE")
        if not (args.all or args.deliverable):
            return 0 if agrees else 1
        if not agrees:
            return 1

    names = sorted(DELIVERABLES) if args.all else (args.deliverable or [])
    if not names:
        parser.error("nothing to do: pass --all, --deliverable, --list or --verify")

    os.makedirs(args.outdir, exist_ok=True)
    for name in names:
        command = (f"sz_paper_profile_extraction.py --deliverable {name} "
                   f"--outdir {args.outdir}")
        document = build(name, command=command)
        path = os.path.join(args.outdir, f"flamingo_{name}.json")
        with open(path, 'w') as f:
            json.dump(document, f, indent=1)
            f.write("\n")
        print(f"{path}: {document['n_stacks']} stacks, "
              f"{os.path.getsize(path) / 1024:.0f} kB")
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
